### ISSUE TITLE
Add link to how to request/create a new account

### ISSUE THREAD

**Issue by basilgohar** [OSC/ood_auth_discovery#5]
SN: INC0308420

> Should we include a link on the ondemand.osc.edu to a web page explaining how to get an account? Perhaps https://www.osc.edu/supercomputing/getting-started/allocations-and-accounts. The link text could be something like "Don't have an OSC account, click here to learn more", but don't listen to me about this, I've added Brian to the incident.

**Comment by ericfranz** [comment]
Add second line: "If you don't have an OSC account, register for one here."

<img width="1024" alt="screen 2018-01-21 at 8 01 34 pm" src="https://user-images.githubusercontent.com/512333/35201061-e8691124-fee5-11e7-9805-f10dc24db458.png">

The URL should be: https://www.osc.edu/resources/getting_started/allocations_and_accounts

This matches the register link on the Keycloak login.
